# Generated by Django 5.1.6 on 2025-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noapp', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='Noname', max_length=100),
        ),
    ]
