# Generated by Django 5.1.6 on 2025-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noapp', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
